Add Azure Arc server VMs support
Strikerzee/azure-storage-azcopy pull request #1
Opened 2021-09-10 14:17 UTC by Strikerzee

2021-09-11 10:32 UTC, linuxsmiths commented on common/oauthTokenManager.go
> -// For details, please refer to https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview
do write a function comment explaining what this function does. Highlight the fact that it sends a token request to the IMDS endpoint passed by the caller, which will be different for Azure and Arc VMs.

2021-09-11 10:32 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +// GetNewTokenFromMSI gets token from Azure Instance Metadata Service identity endpoint.
update the comment to explain how it handles both Azure and Arc VMs by first trying the Azure IMDS endpoint and if that fails it tries the Arc IMDS endpoint.
Also update L730 to add Arc doc link too
https://docs.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication

2021-09-11 10:32 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +	if err != nil {
today the msiTokenHTTPClient timeout is configured for 30 secs. We should discuss with Ze if we can reduce it to 5 secs. 5 secs should be enough as IMDS endpoint is local to the machine.
Without that, if some router is configured to not return "ICMP unreachable" then we will take 30 secs to timeout and fallback to ARC.

2021-09-11 10:32 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +		challengeTokenFile, _ := os.Open(challengeTokenPath)
we should collect err return from os.Open() and emit appropriate errors. For "not found" we should have a Fatal error saying Arc configuration looks improper, for "permission denied" we should warn and suggest that user should belong to himds group. We need to fist check how it behaves on windows.

2021-09-11 10:32 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +		scanner := bufio.NewScanner(challengeTokenFile)
bufio.NewReader() followed by ReadString() seems right for the job, since there's only one line and we don't really need a Scanner. Any specific reason you chose Scanner?

2021-09-11 10:32 UTC, linuxsmiths commented on common/oauthTokenManager.go
>  		return nil, fmt.Errorf("please check whether MSI is enabled on this PC, to enable MSI please refer to https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-c
shouldn't this error be Arc specific?
Azure specific error should already be emitted at L738

2021-09-15 08:24 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +func correctByteSlice(bytes []byte) []byte {
nit. Let's call this fixupTokenJson() which makes the intent clearer.
And the comment above this should explain why we need this. I would put something like this.

// Dated 15th Sep 2021.
// Token JSON returned by ARC currently does not set a valid integral value for "not_before". 
// Fix will be available in future ARC versions, till then use the current time to fixup the byte slice before we pass it to json.Unmarshal().
// If the token JSON already has "not_before" correctly set, this will be a no-op.

Also, this should check if not_before has a null string and only then it should do the fixup, o/w it should be a no-op so that we can handle both cases where not_before is correctly set or not set.

Can we set it to "current time in epoch - 5 secs" just in case someone down the line actually interprets not_before and doesn't like an incorrect value.

2021-09-15 08:24 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +	correctedByteSlice := []byte(correctedString)
nit,
return []byte(correctedString)

2021-09-15 08:24 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +			return nil, fmt.Errorf("please check whether MSI is enabled on this PC, to enable MSI please refer to https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-
Please with P capital

2021-09-15 08:24 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +		if os.IsPermission(fileErr) {
didn't the doc say that this is getting deprecated and we should use the other slightly longer statement?

2021-09-15 08:24 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +		// Create a new Reader for the file.
you should add the following after a successful open

defer challengeTokenFile.Close()

2021-09-15 08:24 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +			return nil, fmt.Errorf("Error occurred while reading file: %v", fileErr)
"Error occurred while opening file %s: %v"

2021-09-15 08:27 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +		b = correctByteSlice(b)
currently it'll not work for Azure VMs which already have the not_before set correctly.
Once you fix it to conditionally set not_before, it'll be fine.

2021-09-15 10:42 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +	separatorString := "\"not_before\":\""
nit, use backtick to avoid backslashes to improve readability.
`"not_before":"`

2021-09-15 10:49 UTC, linuxsmiths commented on common/oauthTokenManager.go
> +	if stringSlice[1][0] == '"' {
to play safe, if not_before is fine, return original slice.. something like

func fixupTokenJson(bytes []byte) []byte {
	byteSliceToString := string(bytes)
	separatorString := `"not_before":"`
	stringSlice := strings.Split(byteSliceToString, separatorString)
	if stringSlice[1][0] != '"' {
	    // Valid value for not_before, return original slice.
	    return bytes
	}

	// Stick in "now-5secs" as not_before value and return the updated slice.
    notBeforeTimeInteger := uint64(time.Now().Unix() - 5)
    notBeforeTime := strconv.FormatUint(notBeforeTimeInteger, 10)
	correctedString := stringSlice[0] + separatorString + notBeforeTime + stringSlice[1]
	return []byte(correctedString)
}

2021-09-15 13:34 UTC, linuxsmiths approved these changes

2021-09-21 02:23 UTC, merged

2021-09-26 00:43 UTC, shalinijoshi19 requested changes
Hey @Strikerzee will you be moving this over to the Azure/Azure-storage-azcopy repo instead of the fork?

2021-10-04 03:44 UTC, Strikerzee commented on common/oauthTokenManager.go
> +	if err != nil {
Changed to 10 seconds